[package]
name = "hiv"
version = "0.1.0"
edition = "2018"
resolver = "2"

[dependencies]
anyhow = "1.0"
winit = "0.25"
wgpu = { git = "https://github.com/gfx-rs/wgpu" }
pollster = "0.2"
bytemuck = { version = "1.7", features = ["derive"] }
